import random
import time#These lines import the 'random' and 'time' modules, which are necessary for the functionality of the guessing game. The 'random' module is used to generate a random number for the user to guess, while the 'time' module is used to measure how long it takes for the user to guess the correct number. By importing these modules, we can utilize their functions in our program to create a more interactive and engaging game experience.

def guessing_game():#This line defines a function named 'guessing_game'. A function is a reusable block of code that performs a specific task. In this case, the 'guessing_game' function contains all the logic for the number guessing game. When this function is called, it will execute the code within its block, allowing the user to play the game.
    print("Welcome to the Guessing Game!")#This line prints a welcome message to the user when they start the game. It serves to greet the user and set a friendly tone for the game.
    print("I'm thinking of a number between 1 and 100.")#This line prints a welcome message to the user and informs them that the game involves guessing a number between 1 and 100. This sets the context for the game and lets the user know what to expect.

    # Generate a random number#This line generates a random integer between 1 and 100 (inclusive) and assigns it to the
    secret_number = random.randint(1, 100)#This line generates a random integer between 1 and 100 (inclusive) and assigns it to the

    # Start timing#This line captures the current time at the start of the game, which is used to calculate the total time taken for the user to guess the correct number. The time is captured using the time.time() function, which returns the current time in seconds since the epoch (January 1, 1970). This allows us to measure how long it takes for the user to guess the correct number by calculating the difference between the end time and this start time later in the program.
    start_time = time.time()#This line captures the current time at the start of the game, which is used to calculate the total time taken for the user to guess the correct number. The time is captured using the time.time() function, which returns the current time in seconds since the epoch (January 1, 1970). This allows us to measure how long it takes for the user to guess the correct number by calculating the difference between the end time and this start time later in the program.

    guess = None#This line initializes the variable 'guess' to None, which is used to store the user's current guess. It is set to None initially because the user has not made any guesses yet. The while loop that follows will continue to execute as long as 'guess' is not equal to the 'secret_number', allowing the user to make guesses until they find the correct number.
    attempts = 0#This line initializes the variable 'attempts' to 0, which is used to keep track of how many guesses the user has made throughout the game. Each time the user makes a guess, this variable will be incremented by 1. When the user eventually guesses the correct number, this variable will be used to display the total number of attempts it took for the user to guess correctly.

    while guess != secret_number:#This line starts a while loop that continues to execute as long as the user's guess is not equal to the secret number. The loop will keep prompting the user to enter their guess and provide feedback until they guess the correct number. Once the user guesses the correct number, the condition will evaluate to False, and the loop will exit, allowing the program to proceed to the next steps (calculating time taken and printing results).
        try:#This line starts a try block that allows the program to handle exceptions that may occur when the user enters their guess. Specifically, it is used to catch a ValueError that may occur if the user enters something that cannot be converted to an integer (e.g., a string or a float). By using a try-except block, the program can provide feedback to the user about what went wrong and prompt them to enter a valid number instead of crashing.
            guess = int(input("Enter your guess: "))#This line prompts the user to enter their guess and attempts to convert the input into an integer. If the user enters something that cannot be converted to an integer (e.g., a string or a float), a ValueError will be raised, which is handled in the except block below. This allows the program to continue running and prompts the user to enter a valid number instead of crashing.
            attempts += 1#This line increments the 'attempts' variable by 1 each time the user makes a guess. This is used to keep track of how many guesses the user has made throughout the game. When the user eventually guesses the correct number, this variable will be used to display the total number of attempts it took for the user to guess correctly.

            if guess < secret_number:#This line is part of the conditional statements that provide feedback to the user based on their guess. If the user's guess is less than the secret number, this line will execute and print the message "Too low, try again." This helps guide the user towards guessing the correct number by indicating whether their guess is too high or too low.
                print("Too low, try again.")#This line is part of the conditional statements that provide feedback to the user based on their guess. If the user's guess is less than the secret number, this line will execute and print the message "Too low, try again." This helps guide the user towards guessing the correct number by indicating whether their guess is too high or too low.
            elif guess > secret_number:#This line is part of the conditional statements that provide feedback to the user based on their guess. If the user's guess is less than the secret number, this line will execute and print the message "Too low, try again." This helps guide the user towards guessing the correct number by indicating whether their guess is too high or too low.
                print("Too high, try again.")#This line is part of the conditional statements that provide feedback to the user based on their guess. If the user's guess is greater than the secret number, this line will execute and print the message "Too high, try again." This helps guide the user towards guessing the correct number by indicating whether their guess is too high or too low.
        except ValueError:#This line starts an exception handling block that catches a ValueError, which occurs when the user enters something that cannot be converted to an integer (e.g., a string or a float). This is important for ensuring that the program does not crash due to invalid input and provides feedback to the user about what went wrong.
            print("Please enter a valid number.")#This line is part of the exception handling block that catches a ValueError, which occurs when the user enters something that cannot be converted to an integer (e.g., a string or a float). When this happens, the program will print the message "Please enter a valid number." and prompt the user to enter their guess again. This helps to ensure that the program does not crash due to invalid input and provides feedback to the user about what went wrong.

    # End timing
    end_time = time.time()#This line captures the current time when the user has guessed the correct number, which is used to calculate the total time taken for the game. The time is captured using the time.time() function, which returns the current time in seconds since the epoch (January 1, 1970). This allows us to measure how long it took for the user to guess the correct number by calculating the difference between the end time and the start time.
    total_time = end_time - start_time#This line calculates the total time taken for the user to guess the correct number by subtracting the start time from the end time. The start time was captured at the beginning of the game, and the end time was captured when the user guessed the correct number. The result is the total time in seconds that it took for the user to guess the correct number.

    print(f"\n🎉 Correct! The number was {secret_number}.")#This line prints a congratulatory message when the user guesses the correct number.
    print(f"You guessed it in {attempts} attempts.")#This line prints the number of attempts it took for the user to guess the correct number. The variable 'attempts' is incremented each time the user makes a guess, so it keeps track of how many guesses the user has made.
    print(f"Time taken: {total_time:.2f} seconds.")#This line prints the total time taken for the user to guess the correct number, formatted to two decimal places. The variable 'total_time' contains the total time in seconds, and the format specifier '.2f' is used to display it with two decimal places for better readability.

# Run the game
guessing_game()#This line calls the function 'guessing_game()' to start the game. When this line is executed, the program will execute all the code within the 'guessing_game()' function, allowing the user to play the guessing game.